#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    Gyro,           sensorGyro)
#pragma config(Sensor, in3,    PotentL,        sensorPotentiometer)
#pragma config(Sensor, in4,    PotentR,        sensorPotentiometer)
#pragma config(Sensor, dgtl3,  Switch0,        sensorTouch)
#pragma config(Sensor, dgtl4,  Switch1,        sensorTouch)
#pragma config(Sensor, dgtl5,  Switch2,        sensorTouch)
#pragma config(Sensor, dgtl6,  TowerLimitL,    sensorTouch)
#pragma config(Sensor, dgtl7,  TowerLimitR,    sensorTouch)
#pragma config(Sensor, dgtl8,  ButtonBlockR,   sensorTouch)
#pragma config(Sensor, dgtl9,  ButtonWait,     sensorTouch)
#pragma config(Sensor, dgtl10, ButtonBlockL,   sensorTouch)
#pragma config(Sensor, dgtl11, TrayPiston,     sensorDigitalOut)
#pragma config(Sensor, dgtl12, PlatformPiston, sensorDigitalOut)
#pragma config(Sensor, I2C_1,  EncoderR,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           DriveRB,       tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port2,           ArmRT,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           RollerR,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port4,           ArmRB,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           DriveRF,       tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port6,           DriveLF,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port7,           ArmLB,         tmotorVex393, openLoop)
#pragma config(Motor,  port8,           RollerL,       tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port9,           ArmLT,         tmotorVex393, openLoop)
#pragma config(Motor,  port10,          DriveLB,       tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_1, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "Worlds_D.c"
#include "Worlds_A.c"

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your rob ot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	//Sensor Value will be the leftmost limit switch is left or right
	//When activated it means left
	//Number 2 chooses agressive or defensive approach
	//When down chooses defensive (Jess or Josh)
	//Down is the alphabetically lower (Samvit or Jess)
	int sum = SensorValue[Switch2] * 4 + SensorValue[Switch1] * 2 + SensorValue[Switch0];
	if (sum == 0) { theSamvit();}
	else if (sum == 1) { theSohum(); }
	else if (sum == 2 || sum == 6) { theJess(); }
	else if (sum == 3) { theJosh(); }
	else if (sum == 4) { theSamvitLeft(); }
	else if (sum == 5) { theSohumLeft(); }
	else if (sum == 7) { theJoshLeft(); }
	//theSohum();
	//theSamvit();
	//theJosh();
	//theJess();
	//theDaniel();
	//theChinmay();
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
  //theSohum();
  //theSamvitLeft();                                                  //f theSamvitLeft();
  //theJoshLeft();
  //theJess();
  //theDaniel();
  //theChinmay();
	driveProgram();
/*setRobot( 0, 'S', 1700, 0, 0, 0, 2000 );

	setRobotPhysLimit(1000, 'S', 1700, 0, 0, 0, 8000);
	setRobot( -350, 'S', 1700, 0, 0, 0, 1200);
	setRobot( 0, 'S', 1700, -127, 1, 0, 800 );
	setRobot( 0, 'S', 1700, 0, 0, 0, 1000 );*/
}
