#pragma config(Sensor, in1,    Gyro,           sensorGyro)
#pragma config(Sensor, in3,    PotentL,        sensorPotentiometer)
#pragma config(Sensor, in4,    PotentR,        sensorPotentiometer)
#pragma config(Sensor, dgtl3,  Switch0,        sensorTouch)
#pragma config(Sensor, dgtl4,  Switch1,        sensorTouch)
#pragma config(Sensor, dgtl5,  Switch2,        sensorTouch)
#pragma config(Sensor, dgtl6,  TowerLimitL,    sensorTouch)
#pragma config(Sensor, dgtl7,  TowerLimitR,    sensorTouch)
#pragma config(Sensor, dgtl8,  ButtonBlockR,   sensorTouch)
#pragma config(Sensor, dgtl9,  ButtonWait,     sensorTouch)
#pragma config(Sensor, dgtl10, ButtonBlockL,   sensorTouch)
#pragma config(Sensor, dgtl11, TrayPiston,     sensorDigitalOut)
#pragma config(Sensor, dgtl12, PlatformPiston, sensorDigitalOut)
#pragma config(Sensor, I2C_1,  EncoderR,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           DriveRB,       tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port2,           ArmRT,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           RollerR,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port4,           ArmRB,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           DriveRF,       tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port6,           DriveLF,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port7,           ArmLB,         tmotorVex393, openLoop)
#pragma config(Motor,  port8,           RollerL,       tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port9,           ArmLT,         tmotorVex393, openLoop)
#pragma config(Motor,  port10,          DriveLB,       tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_1, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "Worlds_U.c"


void testAuton()
{
	//autonProgram();
}

void driveProgram()
{
	resetGyro();
	toggleState_Tray = false;
	toggleState_Platform = false;
	int scoringHeight = 1600;
	int preset = getPotentLValue();

	while( true )
	{
		manualDrive();
		manualFeed();
		pneumaticsCode();

		if( vexRT[Btn5U] == 1 )
		{
			manualArmUpSimple();
			preset = getPotentLValue() + 300;
		}
		else if( vexRT[Btn5D] == 1 )
		{
			manualArmDownSimple();
			preset = getPotentLValue() - 300;
		}
		else if( vexRT[Btn7D] == 1 )
		{
			preset = scoringHeight;
		}
		else
		{
			if( getPotentLValue() > 300 )
			{
				if( SensorValue[ButtonBlockL] == 1 && SensorValue[ButtonBlockR] == 1 )
					moveArm( 3, 3 );
				else if( SensorValue[ButtonBlockL] == 1 && SensorValue[ButtonBlockR] == 0 )
					moveArm( 3, 20 );
				else if( SensorValue[ButtonBlockL] == 0 && SensorValue[ButtonBlockR] == 1 )
					moveArm( 20, 3 );
				else
					setArm( preset );
			}
			else
			{
				if( preset == scoringHeight )
					setArm( preset );
				else
					moveArm( -1, -1 );
			}
		}
	}
}
