#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  foward,         sensorTouch)
#pragma config(Sensor, dgtl2,  redhangingzone, sensorTouch)
#pragma config(Sensor, dgtl3,  bluehangingzone, sensorTouch)
#pragma config(Sensor, dgtl4,  bluemiddlezone, sensorTouch)
#pragma config(Sensor, dgtl5,  solenoid1,      sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           rightbackwheel, tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port2,           rightfrontwheel, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           leftfrontwheel, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightsidearm,  tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port5,           leftsidearm,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           vacuum,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftbackwheel, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;
	while(nMotorEncoder[rightsidearm] < 900)
	{
		motor(port4)=127;         //raise arm and lower scoop/ and release the joner
		motor(port5)=127;
	}
	wait1Msec(100);
	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;
	while(nMotorEncoder[rightbackwheel] > -100)
	{
		motor(port1)=127;
		motor(port2)=127;
		motor(port3)=127;        //knockdown scoop
		motor(port10)=127;

	}
	wait1Msec(100);
	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;
	while(nMotorEncoder[rightsidearm] > -953)
	{
		motor(port4)=-127;
		motor(port5)=-127;      //lower the arm
	}
	nMotorEncoder[rightsidearm] = 0;
	nMotorEncoder[rightbackwheel] = 0;
	wait1Msec(100);
	while(nMotorEncoder[rightbackwheel] > -612)
	{
		motor(port1)=127;
		motor(port2)=127;  //forward getting bucky balls against wall
		motor(port3)=127;
		motor(port10)=127;
	}
wait1Msec(100);
	nMotorEncoder[rightsidearm] = 0;
	nMotorEncoder[rightbackwheel] = 0;


	motor(port6)=127;
	wait1Msec(1000);     // get bucky balls

	motor(port6)=0;
	wait1Msec(100);

	while(nMotorEncoder[rightbackwheel] > -168)
	{
		motor(port1)=127;
		motor(port2)=127;
		motor(port3)=127;     //get the other bucky ball
		motor(port10)=127;

	}
wait1Msec(100);

	motor(port6)=127;
	wait1Msec(1000);

	motor(port6)=127;
	wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;



	while(nMotorEncoder[rightbackwheel] > -1403)
	{
		motor(port1)=127;
		motor(port2)=127;  // swing turn
		motor(port3)=0;
		motor(port10)=0;
	}
wait1Msec(100);

	nMotorEncoder[rightsidearm] = 0;
	nMotorEncoder[rightbackwheel] = 0;

	while(nMotorEncoder[rightbackwheel] < -3737)
	{
		motor(port1)=127;
		motor(port2)=127;  // forward to knock down large ball with dongle
		motor(port3)=127;
		motor(port10)=127;
	}
wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightbackwheel] < 144)
	{
		motor(port1)=-127;
		motor(port2)=-127;
		motor(port3)=127;     //turn right
		motor(port10)=127;

	}

wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;


	while(nMotorEncoder[rightbackwheel] > -364)
	{
		motor(port1)=127;
		motor(port2)=127;     // turn to get ready for cylinder
		motor(port3)=-127;
		motor(port10)=-127;
	}

wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightbackwheel] > -1000)
	{
		motor(port1)=127;
		motor(port2)=127;      //forward
		motor(port3)=127;
		motor(port10)=127;
	}

wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightbackwheel] < 1000)
	{
		motor(port1)=127;
		motor(port2)=127;
		motor(port3)=0;            //turn to cyinder (left)
		motor(port10)=0;
	}
wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;



	while(nMotorEncoder[rightsidearm] < 996)
	{
		motor(port4)=127;     //raise arm
		motor(port5)=127;
	}
wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightbackwheel] > -680)
	{
		motor(port1)=127;
		motor(port2)=127;    //forward to cylinder
		motor(port3)=127;
		motor(port10)=127;
	}
wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	motor(port6)=-127;
	wait1Msec(1000);

	motor(port6)=0;       //stash the bucky balls scoring 15 points
	wait1Msec(100);


	while(nMotorEncoder[rightbackwheel] < 841)
	{
		motor(port1)=-127;
		motor(port2)=-127;     //back up to lower arm
		motor(port3)=-127;
		motor(port10)=-127;
	}
wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightsidearm] > -990)
	{
		motor(port1)=-127;     //lower the arm
		motor(port2)=-127;
	}
wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightbackwheel] < 2192)
	{
		motor(port1)=-127;
		motor(port2)=-127;    //back up to get ready to hit the big ball
		motor(port3)=-127;
		motor(port10)=-127;
	}
wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightbackwheel] < 115)
	{
		motor(port1)=-127;
		motor(port2)=-127;
		motor(port3)=127;    //pivot turn to face large ball
		motor(port10)=127;
	}
	wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;


	while(nMotorEncoder[rightsidearm] < 600)
	{
		motor(port4)=127;    //raise arm to hit big ball
		motor(port5)=127;
	}
	wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;


	while(nMotorEncoder[rightbackwheel] > -752)
	{
		motor(port1)=127;
		motor(port2)=127;      //forward knocking down big balls
		motor(port3)=127;
		motor(port10)=127;
	}
	wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightbackwheel] < 724)
	{
		motor(port1)=-127;
		motor(port2)=-127;       //back up a little bit
		motor(port3)=-127;
		motor(port10)=-127;
	}
	wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightbackwheel] > -215)
	{
		motor(port1)=127;
		motor(port2)=-127;         //turn to face the bucky balls
		motor(port3)=127;
		motor(port10)=-127;
	}
	wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightsidearm] > -410)
	{
		motor(port4)=-127;     //lower arm slightly
		motor(port5)=-127;
	}
	wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightbackwheel] < 746)
	{
		motor(port1)=127;
		motor(port2)=127;          //forward to get the buckyballs
		motor(port3)=127;
		motor(port10)=127;
		motor(port6)=127;
	}
	wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	motor(port6)=127;
	wait1Msec(1000);//intake a bucky ball towards the red side

	motor(port6)=0;
	wait1Msec(100);


	while(nMotorEncoder[rightbackwheel] > -336)
	{
		motor(port1)=127;
		motor(port2)=127;      //swing turn
		motor(port3)=0;
		motor(port10)=0;
	}
wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightbackwheel] > -1875)
	{
		motor(port1)=127;
		motor(port2)=127;
		motor(port3)=127;       //forward
		motor(port10)=127;
	}
	wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;


	while(nMotorEncoder[rightbackwheel] < 295)
	{
		motor(port1)=-127;
		motor(port2)=-127;
		motor(port3)=127;       //turn right to face the bump
		motor(port10)=127;
	}
wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightbackwheel] > -42)
	{
		motor(port1)=127;
		motor(port2)=127;    //turn right
		motor(port3)=-127;
		motor(port10)=-127;
	}
	wait1Msec(100);

	motor(port6)=127;
	wait1Msec(1000);

	motor(port6)=0;
	wait1Msec(100);


	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightbackwheel] <-329)
	{
		motor(port1)=127;
		motor(port2)=127;
		motor(port3)=-127;             // pivot turn to the left
		motor(port10)=-127;

	}
wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightbackwheel] > -1225)
	{
		motor(port1)=127;
		motor(port2)=127;      //forward to blue pre load
		motor(port3)=127;
		motor(port10)=127;
		motor(port6)=127;
	}
wait1Msec(100);

	motor(port6)=127;
	wait1Msec(1000);

	motor(port6)=0;     //get the blue preload filling scoop
	wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightbackwheel] > -1022)
	{
		motor(port1)=127;
		motor(port2)=127;
		motor(port3)=-127;     // turn right
		motor(port10)=-127;
	}
	wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightbackwheel] > -1753)
	{
		motor(port1)=127;
		motor(port2)=127;      //   forward knocking big ball off
		motor(port4)=127;
		motor(port10)=127;
	}
wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;


	while(nMotorEncoder[rightbackwheel] > -1061)
	{
		motor(port1)=127;
		motor(port2)=127;
		motor(port3)=0;          //turn to the left
		motor(port10)=0;
	}

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightbackwheel] > -600)
	{
		motor(port1)=127;
		motor(port2)=127;
		motor(port3)=127;       //forward to get perpendicular to the cylinder          Nick add to this it will be a problem add
		motor(port10)=127;
	}
wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightbackwheel] < 451)
	{
		motor(port1)=-127;
		motor(port2)=-127;         //turn right to get ready for cylinder
		motor(port3)=127;
		motor(port10)=127;
	}
wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightsidearm] < 941)
	{
		motor(port4)=127;          //raise arm to get ready to stash
		motor(port5)=127;
	}
wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightbackwheel] > -941)
	{
		motor(port1)=127;
		motor(port2)=127;             //forward to straddle cylinder
		motor(port3)=127;
		motor(port10)=127;
	}
wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	motor(port6)=-127;
	wait1Msec(1000);

	motor(port6)=0;
	wait1Msec(100);

	while(nMotorEncoder[rightbackwheel] < 769)
	{
		motor(port1)=-127;
		motor(port2)=-127;
		motor(port3)=-127;         //back up
		motor(port10)=-127;
	}
wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightsidearm] > -953)
	{
		motor(port4)=-127;
		motor(port5)=-127;         //lower arm
	}
wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightbackwheel] < 1678)
	{
		motor(port1)=-127;
		motor(port2)=-127;           //back up to get under the barrier
		motor(port3)=-127;
		motor(port10)=-127;
	}
wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightbackwheel] > -168)
{
	motor(port1)=127;
	motor(port2)=127;                //turn to face large ball
	motor(port3)=-127;
	motor(port10)=-127;
}
wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;


	while(nMotorEncoder[rightsidearm] < 541)
	{
		motor(port4)=127;
		motor(port5)=127;      //raise arm to knock down big ball
	}
wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;

	while(nMotorEncoder[rightbackwheel] > -570)
	{
		motor(port1)=127;
		motor(port2)=127;
		motor(port3)=127;
		motor(port10)=127;
	}
wait1Msec(100);

	nMotorEncoder[rightbackwheel] = 0;
	nMotorEncoder[rightsidearm] = 0;




}
