#pragma config(Motor,  port1,           motLeftWheel1, tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port2,           motLeftWheel2, tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port3,           motRightWheel1, tmotorVex269, openLoop)
#pragma config(Motor,  port4,           motRightWheel2, tmotorVex269, openLoop)
#pragma config(Motor,  port5,           motLiftLeft,   tmotorVex393, openLoop)
#pragma config(Motor,  port6,           motLiftRight,  tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           motJointLeft,  tmotorVex393, openLoop)
#pragma config(Motor,  port8,           motJointRight, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           motFeed,       tmotorVex393, openLoop)
#pragma config(Motor,  port10,          motTray,       tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//Speed constants
int LIFT_SPEED = 127;
int JOINT_SPEED = 80;
int TRAY_SPEED = 80;
int FEED_SPEED = 80;

//Controls
TVexJoysticks CHANNEL_RIGHT = Ch3;
TVexJoysticks CHANNEL_LEFT = Ch3;
TVexJoysticks CHANNEL_LIFTUP = Btn6U;
TVexJoysticks CHANNEL_LIFTDOWN = Btn6D;
TVexJoysticks CHANNEL_JOINTUP = Btn5U;
TVexJoysticks CHANNEL_JOINTDOWN = Btn5D;
TVexJoysticks CHANNEL_TRAYUP = Btn7U;
TVexJoysticks CHANNEL_TRAYDOWN = Btn7D;
TVexJoysticks CHANNEL_FEEDUP = Btn8U;
TVexJoysticks CHANNEL_FEEDDOWN = Btn8D;

//Initialization
void pre_auton()
{

}

//Autonomous mode
task autonomous()
{

}
void autonRedOne()
{

}
	/*Red 1 -

		Move forward - Cross Barrier - Slow - Lift Arm - Hit Goal - Wait
		Move backward - Stop - Low Arm - Move backward
			[User Adjust]
		Move forward hit big ball
		Move back
			[User Adjust]
		Move Forward hit Big ball

	*/

//User control mode
task usercontrol()
{
	int rightMotSpeed = 0, leftMotSpeed = 0, liftMotSpeed = 0, jointMotSpeed = 0, trayMotSpeed = 0, feedMotSpeed = 0;

	while (true)
	{
		//Vanilla values of inputs

	//TANKMETHOD


	/*
		rightMotSpeed = vexRT[CHANNEL_RIGHT]^2/127;
		leftMotSpeed = vexRT[CHANNEL_LEFT]^2/127;
		liftMotSpeed = (vexRT[CHANNEL_LIFTUP]*LIFT_SPEED)-(vexRT[CHANNEL_LIFTDOWN]*LIFT_SPEED);
		jointMotSpeed = (vexRT[CHANNEL_JOINTUP]*JOINT_SPEED)-(vexRT[CHANNEL_JOINTDOWN]*JOINT_SPEED);
		trayMotSpeed = (vexRT[CHANNEL_TRAYUP]*TRAY_SPEED)-(vexRT[CHANNEL_TRAYDOWN]*TRAY_SPEED);
		feedMotSpeed = (vexRT[CHANNEL_FEEDUP]*FEED_SPEED)-(vexRT[CHANNEL_FEEDDOWN]*FEED_SPEED);
		*/

	//HALO CONFIGS

		//rightMotSpeed = vexRT(Ch3)^2/127-(vexRT(Ch1)^2/127)*1/2;
		//leftMotSpeed = vexRT(Ch3)^2/127+(vexRT(Ch1)^2/127)*1/2;


		liftMotSpeed = (vexRT[CHANNEL_LIFTUP]*LIFT_SPEED)-(vexRT[CHANNEL_LIFTDOWN]*LIFT_SPEED);
		jointMotSpeed = (vexRT[CHANNEL_JOINTUP]*JOINT_SPEED)-(vexRT[CHANNEL_JOINTDOWN]*JOINT_SPEED);
		trayMotSpeed = (vexRT[CHANNEL_TRAYUP]*TRAY_SPEED)-(vexRT[CHANNEL_TRAYDOWN]*TRAY_SPEED);
		feedMotSpeed = (vexRT[CHANNEL_FEEDUP]*FEED_SPEED)-(vexRT[CHANNEL_FEEDDOWN]*FEED_SPEED);

		if(Ch3 != 0 && Ch1 == 0)	//
		{
			rightMotSpeed = vexRT(Ch3)^2/127;
			leftMotSpeed = rightMotSpeed;
		}
		else if(Ch3 == 0 && Ch1 != 0)
		{
			rightMotSpeed = vexRT(Ch1)^2/127*(-1);
			leftMotSpeed = -rightMotSpeed;
		}
		else if (Ch3 != 0 && Ch1 != 0)
		{
			rightMotSpeed = 0;
			leftMotSpeed = rightMotSpeed;
		}

//future sensor


		//Set all motors to their respective values
		motor[motRightWheel1] = motor[motRightWheel2] = rightMotSpeed; //
		motor[motLeftWheel1] = motor[motLeftWheel2] = leftMotSpeed;
		motor[motLiftRight] = motor[motLiftLeft] = liftMotSpeed;
		motor[motJointRight] = motor[motJointLeft] = jointMotSpeed;
		/*setTwoMotors(motRightWheel1, motRightWheel2, rightMotSpeed);
		setTwoMotors(motLeftWheel1, motLeftWheel2, leftMotSpeed);
		setTwoMotors(motLiftRight, motLiftLeft, liftMotSpeed);
		setTwoMotors(motJointRight, motJointLeft, jointMotSpeed);*/
		motor[motTray] = trayMotSpeed;
		motor[motFeed] = feedMotSpeed;
	}

	/*void setTwoMotors(tMotor mot1, tMotor mot2, int val) {
		motor[mot1] = motor[mot2] = val;
	}*/
}

/*int normalizeButtons(TVexJoysticks channelUp, TVexJoysticks channelDown, int spd) {
	return (vexRT[channelUp]*spd)-(vexRT[channelDown]*spd);
}*/
