#pragma config(Motor,  port1,           LeftLift,      tmotorVex393, openLoop)
#pragma config(Motor,  port2,           LeftCloseWheel, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           LeftMidWheel,  tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port4,           LeftFarWheel,  tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port5,           LeftIntake,    tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port6,           RightIntake,   tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port7,           RightFarWheel, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port8,           RightMidWheel, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port9,           RightCloseWheel, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port10,          RightLift,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//Speed constants

/*int LIFT_SPEED = 127;
int JOINT_SPEED = 80;
int TRAY_SPEED = 80;
int FEED_SPEED = 80;
*/

//Controls
/*
	TVexJoysticks RIGHT = Ch3;
	TVexJoysticks LEFT = Ch3;
	TVexJoysticks LIFT_UP = Btn5U;
	TVexJoysticks LIFT_DOWN = Btn5D;
	TVexJoysticks INTAKE_IN = Btn6U;
	TVexJoysticks INTAKE_OUT = Btn6D;
	TVexJoysticks CHANNEL_TRAYUP = Btn7U;
	TVexJoysticks CHANNEL_TRAYDOWN = Btn7D;
	TVexJoysticks CHANNEL_FEEDUP = Btn8U;
	TVexJoysticks CHANNEL_FEEDDOWN = Btn8D;
*/

//Initialization
void pre_auton()
{

}

//Autonomous mode
task autonomous()
{

}
void autonRedOne()
{

}
	/*Red 1 -

		Move forward - Cross Barrier - Slow - Lift Arm - Hit Goal - Wait
		Move backward - Stop - Low Arm - Move backward
			[User Adjust]
		Move forward hit big ball
		Move back
			[User Adjust]
		Move Forward hit Big ball

	*/

//User control mode
task usercontrol()
{
	int rightDrSpd = 0.0, leftDrSpd = 0.0, liftSpd = 0.0, intakeSpd = 0.0;

	while (true)
	{
		//Vanilla values of inputs

	//TANKMETHOD


	/*
		rightMotSpeed = vexRT[CHANNEL_RIGHT]^2/127;
		leftMotSpeed = vexRT[CHANNEL_LEFT]^2/127;
		liftMotSpeed = (vexRT[CHANNEL_LIFTUP]*LIFT_SPEED)-(vexRT[CHANNEL_LIFTDOWN]*LIFT_SPEED);
		jointMotSpeed = (vexRT[CHANNEL_JOINTUP]*JOINT_SPEED)-(vexRT[CHANNEL_JOINTDOWN]*JOINT_SPEED);
		trayMotSpeed = (vexRT[CHANNEL_TRAYUP]*TRAY_SPEED)-(vexRT[CHANNEL_TRAYDOWN]*TRAY_SPEED);
		feedMotSpeed = (vexRT[CHANNEL_FEEDUP]*FEED_SPEED)-(vexRT[CHANNEL_FEEDDOWN]*FEED_SPEED);
		*/

	//-------------HALO CONFIGS---------------

		//rightMotSpeed = vexRT(Ch3)^2/127-(vexRT(Ch1)^2/127)*1/2;
		//leftMotSpeed = vexRT(Ch3)^2/127+(vexRT(Ch1)^2/127)*1/2;

/*
		liftMotSpeed = (vexRT[CHANNEL_LIFTUP]*LIFT_SPEED)-(vexRT[CHANNEL_LIFTDOWN]*LIFT_SPEED);
		jointMotSpeed = (vexRT[CHANNEL_JOINTUP]*JOINT_SPEED)-(vexRT[CHANNEL_JOINTDOWN]*JOINT_SPEED);
		trayMotSpeed = (vexRT[CHANNEL_TRAYUP]*TRAY_SPEED)-(vexRT[CHANNEL_TRAYDOWN]*TRAY_SPEED);
		feedMotSpeed = (vexRT[CHANNEL_FEEDUP]*FEED_SPEED)-(vexRT[CHANNEL_FEEDDOWN]*FEED_SPEED);

		if(Ch3 != 0 && Ch1 == 0)	//
		{
			rightMotSpeed = vexRT(Ch3)^2/127;
			leftMotSpeed = rightMotSpeed;
		}
		else if(Ch3 == 0 && Ch1 != 0)
		{
			rightMotSpeed = vexRT(Ch1)^2/127*(-1);
			leftMotSpeed = -rightMotSpeed;
		}
		else if (Ch3 != 0 && Ch1 != 0)
		{
			rightMotSpeed = 0;
			leftMotSpeed = rightMotSpeed;
		}
*/

	rightDrSpd = vexRT(Ch3)*vexRT(Ch3)/127.0 - vexRT(Ch1)*vexRT(Ch1)/127.0; // Left Joystick power -> Minus Right Joystick value to turn - right--, left++
	leftDrSpd = vexRT(Ch3)*vexRT(Ch3)/127.0 + vexRT(Ch1)*vexRT(Ch1)/127.0;	// Left Joystick power -> Add Right Joystick value to turn - right++, left--

//leftDrSpd = vexRT(Ch3);
		//Set Motors
		/*
		motor[motRightWheel1] = motor[motRightWheel2] = rightMotSpeed; //
		motor[motLeftWheel1] = motor[motLeftWheel2] = leftMotSpeed;
		motor[motLiftRight] = motor[motLiftLeft] = liftMotSpeed;
		motor[motJointRight] = motor[motJointLeft] = jointMotSpeed;

		setTwoMotors(motRightWheel1, motRightWheel2, rightMotSpeed);
		setTwoMotors(motLeftWheel1, motLeftWheel2, leftMotSpeed);
		setTwoMotors(motLiftRight, motLiftLeft, liftMotSpeed);
		setTwoMotors(motJointRight, motJointLeft, jointMotSpeed);

		motor[motTray] = trayMotSpeed;
		motor[motFeed] = feedMotSpeed;

		*/
		motor[LeftCloseWheel] =  motor[LeftMidWheel] = motor[LeftFarWheel] = leftDrSpd;
		motor[RightCloseWheel] = motor[RightMidWheel] = motor[RightFarWheel] = rightDrSpd;
	}

	/*void setTwoMotors(tMotor mot1, tMotor mot2, int val) {
		motor[mot1] = motor[mot2] = val;
	}*/
}

/*int normalizeButtons(TVexJoysticks channelUp, TVexJoysticks channelDown, int spd) {
	return (vexRT[channelUp]*spd)-(vexRT[channelDown]*spd);
}*/
